repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0-1
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
-   repo: local
    hooks:
    - id: format
      name: fmt
      entry: make fmt
      language: system
      files: \.(go)$
    - id: vet
      name: vet
      entry: make vet
      language: system
      files: \.(go)$
