name: "Building release binaries on Windows"

on: [push]

jobs:
  Windows-Build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1

          choco install -y golang --version=1.14
          refreshenv
          go

#          $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
#          $env:GOROOT = [System.Environment]::GetEnvironmentVariable("GOROOT", "Machine")
#          $env:GOPATH = "$env:UserProfile\go"
#          $env:Path = $env:Path + ";" + $env:GOPATH + "\bin"
#          Get-Childitem –Path C:\ -Include go* -Recurse -ErrorAction SilentlyContinue

          go generate ./...
          go build -o bin/yubihsm-connector.exe

          ls 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools'
          Get-Childitem –Path C:\ -Include VsMSBuildCmd.bat -Recurse -ErrorAction SilentlyContinue

          cd win-installer
          cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsMSBuildCmd.bat" && msbuild YubiHSMConnectorInstaller.sln /p:Configuration=Release'

          mkdir artifact
          Copy-Item x64/Release/yubihsm-connector-windows-amd64.msi -Destination artifact\

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubihsm-connector-windows-amd64
          path: artifact